/**
 * Detailed Schedule K-1 (Form 1065) types for partnership tax reporting.
 * Covers all parts of the K-1 worksheet as generated by TurboTax.
 */

// ============================================================================
// K-1 PART I — INFORMATION ABOUT THE PARTNERSHIP
// ============================================================================

export interface K1PartnershipInfo {
  ein: string
  name: string
  address?: string | null
  cityStateZip?: string | null
  isPubliclyTradedPartnership?: boolean
  isForeignPartnership?: boolean
}

// ============================================================================
// K-1 PART II — INFORMATION ABOUT THE PARTNER
// ============================================================================

export interface K1PartnerInfo {
  partnerName: string
  partnerSSN: string
  partnerAddress?: string | null
  partnerCityStateZip?: string | null
  isGeneralPartner: boolean
  isDomesticPartner: boolean
  entityType: string
  /** Profit/loss/capital share percentages (beginning and ending) */
  profitShareBeginning?: number | null
  profitShareEnding?: number | null
  lossShareBeginning?: number | null
  lossShareEnding?: number | null
  capitalShareBeginning?: number | null
  capitalShareEnding?: number | null
  /** Partner's share of liabilities */
  nonrecourseDebt?: number | null
  qualifiedNonrecourseDebt?: number | null
  recourseDebt?: number | null
  allInvestmentAtRisk: boolean
  /** Capital account analysis */
  capitalAccountBeginning?: number | null
  capitalContributedDuringYear?: number | null
  currentYearNetIncomeLoss?: number | null
  otherIncreaseDecrease?: number | null
  withdrawalsDistributions?: number | null
  capitalAccountEnding?: number | null
}

// ============================================================================
// K-1 PART III — CODED BOX ITEMS
// ============================================================================

/** Box 11: Other income (loss) coded entries */
export interface K1Box11OtherIncome {
  /** Code A: Other portfolio income (loss) */
  codeA_otherPortfolioIncome?: number | null
  /** Code A detail (e.g. "MISC INCOME FROM TAU VENTURES K-1") */
  codeA_detail?: string | null
  /** Code B: Involuntary conversions */
  codeB_involuntaryConversions?: number | null
  /** Code C: Section 1256 contracts and straddles */
  codeC_sec1256ContractsStraddles?: number | null
  /** Code S: Non-portfolio capital gain (loss) */
  codeS_nonPortfolioCapitalGain?: number | null
  /** Code ZZ: Other income — carries nonpassive items to Schedule E page 2 */
  codeZZ_otherIncome?: number | null
  /** Itemized breakdown of code ZZ (e.g. NET SECTION 988, SWAP INCOME, MARK TO MARKET) */
  codeZZ_detail?: Array<{ description: string; amount: number }>
}

/** Box 13: Other deductions coded entries */
export interface K1Box13OtherDeductions {
  /** Code AE: Deductions – portfolio income (2% floor misc itemized) */
  codeAE_portfolioDeductions?: number | null
  /** Code H: Investment interest expense (Form 4952) */
  codeH_investmentInterestExpense?: number | null
  /** Code L: Deductions – portfolio income (other) */
  codeL_otherPortfolioDeductions?: number | null
  /** Code ZZ: Other deductions (carries to Schedule E page 2) */
  codeZZ_otherDeductions?: number | null
  /** Itemized breakdown of code ZZ (e.g. Trader Deductions, Admin Expenses) */
  codeZZ_detail?: Array<{ description: string; amount: number }>
}

/** Box 19: Distributions */
export interface K1Box19Distributions {
  /** Code A: Cash and marketable securities */
  codeA_cashAndMarketableSecurities?: number | null
  /** Code B: Distribution subject to section 737 */
  codeB_section737?: number | null
  /** Code C: Other property */
  codeC_otherProperty?: number | null
}

/** Box 20: Other information */
export interface K1Box20OtherInformation {
  /** Code A: Investment income */
  codeA_investmentIncome?: number | null
  /** Code B: Investment expenses */
  codeB_investmentExpenses?: number | null
  /** Code AA: Section 704(c) information */
  codeAA_sec704cInfo?: number | null
  /** Code AJ: Excess business loss limitation (IRC 461(l)) */
  codeAJ_excessBusinessLossLimitation?: number | null
  /** Code ZZ: Other information */
  codeZZ_other?: number | null
}

// ============================================================================
// K-1 WORKSHEET SECTIONS (TurboTax generated)
// ============================================================================

/** Section A: Passive Activity Adjustment (Regular Tax and AMT purposes) */
export interface K1PassiveActivityEntry {
  description: string
  gainLossForm6198?: number | null
  suspendedLossCarryoverFromPriorYear?: number | null
  netIncomeAllowed?: number | null
  lossSuspendedCurrentYear?: number | null
}

export interface K1PassiveActivityWorksheet {
  activityNetIncomeLoss?: number | null
  passiveOrNonpassiveClassification?: string | null
  /** Part 5: Short-term capital gain entries */
  shortTermCapitalGain?: K1PassiveActivityEntry[]
  /** Part 6: Long-term capital gain entries */
  longTermCapitalGain?: K1PassiveActivityEntry[]
  /** Line 9 total: combine all */
  totalNetIncomeLoss?: number | null
}

/** Section C: Income and Loss Reported on Schedule E */
export interface K1ScheduleEEntry {
  lineNumber: number
  /** Line 28T code (e.g. 'D', 'E', 'F') */
  code: string
  description: string
  passiveLossK1?: number | null
  passiveIncomeK1?: number | null
  nonpassiveLossK1?: number | null
  section179?: number | null
  nonpassiveIncomeK1?: number | null
}

/** Section D1: QBI Statement A Information */
export interface K1QBIStatementAInfo {
  tradeOrBusiness?: string | null
  ein?: string | null
  isPTP: boolean
  isAggregated: boolean
  isSSFB: boolean
  ordinaryBusinessIncome?: number | null
  rentalIncomeLoss?: number | null
  royaltyIncomeLoss?: number | null
  section1231GainLoss?: number | null
  otherIncomeLoss?: number | null
  section179Deduction?: number | null
  otherDeductions?: number | null
  w2Wages?: number | null
  ubiaOfQualifiedProperty?: number | null
  section199aDividends?: number | null
}

/** Section D2: QBI Deduction Info */
export interface K1QBIDeductionInfo {
  includesSection199ABusiness: boolean
  statementAInfo?: K1QBIStatementAInfo | null
}

// ============================================================================
// K-1 ADDITIONAL INFORMATION WORKSHEET
// (TurboTax: "Schedule K-1 Partnership Additional Information")
// Covers boxes 9c, 11, 12, 13, 15, 16, 17, 18, 20 detail
// ============================================================================

export interface K1Box16ForeignTransactions {
  lineH_grossIncomeFromOtherCategories?: number | null
  grossIncomeAtPartnerLevel_total?: number | null
  grossIncomeAtPartnerLevel_usSource?: number | null
  grossIncomeAtPartnerLevel_foreign?: number | null
  interestExpenseAtPartnerLevel?: number | null
  otherExpensesAtPartnerLevel_total?: number | null
  otherExpensesAtPartnerLevel_usSource?: number | null
  otherExpensesAtPartnerLevel_foreign?: number | null
  foreignTaxesPaidDate?: string | null
  claimCreditOrDeduction: 'credit' | 'deduction'
  /** Form 1116 copy link (e.g. "COPY 1") */
  form1116Copy?: string | null
  /** Form 1116 column selected (A, B, or C) */
  form1116Column?: string | null
}

export interface K1AdditionalInfoWorksheet {
  partnershipName: string
  box9c_unrecapturedSec1250Gain?: {
    includedInNetSec1231Gain?: number | null
    includedInLTGainFromEstateTrust?: number | null
    includedInLTGainFromPartnershipDisposition?: number | null
    totalBox9c?: number | null
  }
  box11_detail?: K1Box11OtherIncome
  box12_section179Detail?: {
    carryoverFromPriorYear?: number | null
    currentYearAllowed?: number | null
    totalBox12CodeW?: number | null
  }
  box13_detail?: K1Box13OtherDeductions
  box16_detail?: K1Box16ForeignTransactions
  box17_amtItems?: Record<string, number | null>
  box18_taxExemptNondeductible?: Record<string, number | null>
  box20_detail?: K1Box20OtherInformation
}

// ============================================================================
// SCHEDULE K-3 — FOREIGN TRANSACTIONS WORKSHEET
// ============================================================================

export interface ScheduleK3ForeignTransactions {
  partnershipName: string
  countryOrTerritory: string
  grossIncomeAllSources?: number | null
  grossIncomeAtPartnerLevel?: number | null
  foreignBranchCategory?: number | null
  foreignGrossIncomePassive?: number | null
  foreignGrossIncomeGeneral?: number | null
  foreignGrossIncomeOther?: number | null
  deductionInterestExpense?: number | null
  deductionOther?: number | null
  deductionsPassiveCategory?: number | null
  deductionsGeneralCategory?: number | null
  totalForeignTaxesPaid?: number | null
  totalForeignTaxesAccrued?: number | null
}

// ============================================================================
// COMPLETE SCHEDULE K-1 (FORM 1065) RECORD
// ============================================================================

export interface ScheduleK1Form1065 {
  taxYear: number
  isFinal: boolean
  isAmended: boolean
  partI: K1PartnershipInfo
  partII: K1PartnerInfo
  /** Type of activity reported */
  activityTypes: {
    business: boolean
    rentalRealEstate: boolean
    otherRentalActivities: boolean
    other: boolean
    multipleTypes: boolean
  }
  // --- Part III: Partner's Share of Current Year Income, Deductions, Credits ---
  box1_ordinaryBusinessIncome?: number | null
  box2_netRentalRealEstate?: number | null
  box3_otherNetRental?: number | null
  box4a_guaranteedPaymentsServices?: number | null
  box4b_guaranteedPaymentsCapital?: number | null
  box4c_guaranteedPaymentsTotal?: number | null
  box5_interestIncome?: number | null
  box5_usObligationsIncluded?: number | null
  box6a_ordinaryDividends?: number | null
  box6b_qualifiedDividends?: number | null
  box6c_dividendEquivalents?: number | null
  box6_usObligationsIncluded?: number | null
  box7_royalties?: number | null
  box8_netShortTermCapitalGainLoss?: number | null
  box9a_netLongTermCapitalGainLoss?: number | null
  box9b_collectibles28Gain?: number | null
  box9c_unrecapturedSec1250Gain?: number | null
  box10_netSec1231GainLoss?: number | null
  box11_otherIncome?: K1Box11OtherIncome
  box12_section179Deduction?: number | null
  box13_otherDeductions?: K1Box13OtherDeductions
  box14_selfEmploymentEarnings?: Record<string, number | null>
  box15_credits?: Record<string, number | null>
  /** True if Schedule K-3 is attached */
  box16_scheduleK3Attached?: boolean
  box17_amtItems?: Record<string, number | null>
  box18_taxExemptNondeductible?: Record<string, number | null>
  box19_distributions?: K1Box19Distributions
  box20_otherInformation?: K1Box20OtherInformation
  box21_foreignTaxesPaidOrAccrued?: number | null
  // --- TurboTax worksheet sections ---
  sectionA_passiveActivity?: K1PassiveActivityWorksheet
  sectionA_amt?: K1PassiveActivityWorksheet
  sectionC_scheduleEReporting?: K1ScheduleEEntry[]
  sectionD1_qbiStatementA?: K1QBIStatementAInfo
  sectionD2_qbiDeductionInfo?: K1QBIDeductionInfo
  additionalInfoWorksheet?: K1AdditionalInfoWorksheet
  scheduleK3?: ScheduleK3ForeignTransactions
}
