import type { RothConversionInputs } from './types'

export const DEFAULT_ROTH_CONVERSION_INPUTS: RothConversionInputs = {
  currentYear: new Date().getFullYear(),
  filingStatus: 'married_filing_jointly',
  people: {
    primaryBirthYear: new Date().getFullYear() - 58,
    primaryCurrentAge: 58,
    primaryEndAge: 95,
    spouseBirthYear: new Date().getFullYear() - 56,
    spouseCurrentAge: 56,
    spouseEndAge: 95,
    firstDeathAge: null,
  },
  income: {
    wagesPrimary: 180_000,
    wagesSpouse: 0,
    retirementAgePrimary: 62,
    retirementAgeSpouse: 62,
    selfEmploymentPrimary: 0,
    selfEmploymentSpouse: 0,
    interest: 8_000,
    taxExemptInterest: 0,
    qualifiedDividends: 12_000,
    longTermCapitalGains: 10_000,
    otherOrdinary: 20_000,
  },
  socialSecurity: {
    piaPrimary: 3_200,
    piaSpouse: 1_600,
    fraPrimary: 67,
    fraSpouse: 67,
    claimAgePrimary: 70,
    claimAgeSpouse: 67,
    colaPercent: 2.5,
  },
  balances: {
    traditionalPrimary: 900_000,
    traditionalSpouse: 350_000,
    rothPrimary: 180_000,
    rothSpouse: 80_000,
    hsa: 35_000,
    taxableBrokerage: 450_000,
    taxableBasis: 320_000,
    cash: 90_000,
  },
  strategy: {
    name: 'Convert to top of 24%',
    conversionMode: 'fill_bracket',
    conversionStartAge: 62,
    conversionEndAge: 72,
    annualConversion: 60_000,
    bracketTarget: 24,
    perYearConversions: {},
    harvestLtcg: true,
    ltcgTargetRate: 0,
    withdrawalOrder: 'tax_deferred_taxable_roth',
  },
  scenarios: [
    { name: 'Convert to top of 24%', strategy: {} },
    { name: 'No conversion', strategy: { conversionMode: 'constant', annualConversion: 0 } },
    { name: 'Top of 12%', strategy: { conversionMode: 'fill_bracket', bracketTarget: 12 } },
  ],
  assumptions: {
    preRetirementGrowthPercent: 6,
    postRetirementGrowthPercent: 5,
    inflationPercent: 2.5,
    stateTaxPercent: 5,
    stateTaxesLtcg: true,
    deductionMode: 'standard',
    customDeduction: 0,
    discountRatePercent: 3,
    priorYearMagi: 0,
    twoYearsPriorMagi: 0,
  },
}
