import { BOX20_CODES } from '../k1-codes'

describe('BOX20_CODES', () => {
  it('uses TY 2024 Schedule K-1 Box 20 labels for renumbered and extended codes', () => {
    expect(BOX20_CODES).toMatchObject({
      I: 'Recapture of other credits (TY 2023+; Look-back interest—completed long-term contracts pre-2023)',
      J: 'Look-back interest—completed long-term contracts (TY 2023+; Look-back interest—income forecast method pre-2023)',
      K: 'Look-back interest—income forecast method (TY 2023+; Dispositions of property with section 179 deductions pre-2023)',
      L: 'Dispositions of property with section 179 deductions (TY 2023+; Recapture of section 179 deduction pre-2023)',
      M: 'Recapture of section 179 deduction (TY 2023+; Section 453(l)(3) information pre-2023)',
      N: 'Business interest expense (information item) (TY 2023+; Section 453A(c) information pre-2023)',
      O: 'Section 453(l)(3) information (TY 2023+; Section 1260(b) information pre-2023)',
      P: 'Section 453A(c) information (TY 2023+; interest allocable to production expenditures pre-2023)',
      Q: 'Section 1260(b) information (TY 2023+; Section 409A income pre-2023)',
      R: 'Interest allocable to production expenditures (TY 2023+; Section 448(d)(5) deferral pre-2023)',
      S: 'Capital construction fund (CCF) nonqualified withdrawals (TY 2023+; Section 199A information pre-2023)',
      T: 'Depletion deduction (TY 2023+; Section 704(c) information pre-2023)',
      U: 'Section 743(b) basis adjustment (TY 2023+; net investment income pre-2023)',
      V: 'Unrelated business taxable income (TY 2023+; Section 199A UBIA of qualified property pre-2023)',
      W: 'Precontribution gain (loss) (TY 2023+; Section 965 information pre-2023)',
      X: 'Payment obligations including guarantees and deficit obligations (DROs) (TY 2024+; Section 461(l) excess business loss information pre-2023)',
      Y: 'Net investment income (TY 2023+; other information pre-2023)',
      Z: 'Section 199A information (TY 2023+; Section 1061 information pre-2023)',
      AA: 'Section 704(c) information (TY 2023+)',
      AB: 'Section 751 gain (loss)',
      AC: 'Section 1(h)(5) collectibles gain',
      AD: 'Section 1(h)(6) unrecaptured section 1250 gain',
      AE: 'Excess taxable income',
      AF: 'Excess business interest income',
      AG: 'Gross receipts for section 448(c)',
      AH: 'Noncash charitable contributions',
      AI: 'Interest and tax on deferred compensation to partners',
      AJ: 'Excess business loss limitation',
      AK: 'Gain from mark-to-market election',
      AL: 'Section 721(c) partnership',
      AM: 'Section 1061 information',
      AN: 'Farming and fishing business',
      AO: 'PTP information',
      AP: 'Inversion gain',
      AQ: 'Conservation reserve program payments',
      AR: 'IRA disclosure',
      AS: 'Qualifying advanced coal project property and qualifying gasification project property',
      AT: 'Qualifying advanced energy project property',
      AU: 'Advanced manufacturing investment property',
      AV: 'Reserved for future use',
      AW: 'Reportable transactions',
      AX: 'Corporate alternative minimum tax (CAMT)',
      AY: 'Foreign partners, Form 8990, Schedule A',
      AZ: 'Reserved for future use',
      BA: 'Reserved for future use',
      BB: 'Reserved for future use',
      BC: 'Reserved for future use',
      BD: 'Reserved for future use',
      ZZ: 'Other',
    })
  })
})
