<?php

namespace App\Http\Controllers\Agent;

use App\Http\Controllers\Controller;
use App\Support\Agent\AgentContext;
use App\Support\Agent\Capability;
use App\Support\Agent\CapabilityRegistry;
use App\Support\Payload\AgentPayload;
use Illuminate\Http\JsonResponse;
use stdClass;

/**
 * GET /api/agent/v1/openapi.json — OpenAPI 3.1 document generated by hand
 * from the capability registry (no codegen dependency).
 *
 * Only capabilities visible to the caller appear: anonymous requests yield a
 * public-only document, and token scopes shrink it further. Capabilities are
 * emitted in stable id order so snapshots are deterministic.
 */
class AgentOpenApiController extends Controller
{
    private const OUTPUT_FORMATS = ['application/json', AgentPayload::TOON_MEDIA_TYPE];

    public function __construct(private readonly CapabilityRegistry $registry) {}

    public function __invoke(AgentContext $context): JsonResponse
    {
        $visible = array_values(array_filter(
            $this->registry->visibleTo($context),
            fn (Capability $capability): bool => $capability->restMethod !== null && $capability->restPath !== null,
        ));

        usort($visible, fn (Capability $a, Capability $b): int => strcmp($a->id, $b->id));

        $paths = [];

        foreach ($visible as $capability) {
            $paths[(string) $capability->restPath][strtolower((string) $capability->restMethod)] =
                $this->operation($capability);
        }

        return response()->json([
            'openapi' => '3.1.0',
            'info' => [
                'title' => 'BH Agent API',
                'description' => 'Capability-filtered agent surface. Unavailable capabilities are omitted from this document; direct unauthorized calls return 403 (401 when unauthenticated).',
                'version' => '1',
            ],
            'servers' => [
                ['url' => url('/api/agent/v1')],
            ],
            'components' => [
                'securitySchemes' => [
                    'bearerAuth' => [
                        'type' => 'http',
                        'scheme' => 'bearer',
                    ],
                ],
            ],
            'paths' => $paths === [] ? new stdClass : $paths,
        ]);
    }

    /** @return array<string, mixed> */
    private function operation(Capability $capability): array
    {
        $operation = [
            'operationId' => $capability->id,
            'summary' => $capability->label,
            'description' => $capability->description,
            'tags' => [$capability->openApiTag !== '' ? $capability->openApiTag : $capability->module],
            'security' => $capability->isPublic() ? [] : [['bearerAuth' => []]],
            'x-bh-module' => $capability->module,
            'x-bh-capability' => $capability->id,
            'x-bh-required-permission' => $capability->requiredPermission,
            'x-bh-risk' => $capability->risk,
            'x-bh-mcp-tool' => $capability->mcpTool,
            'x-bh-output-formats' => self::OUTPUT_FORMATS,
        ];

        if ($capability->requestSchema !== null) {
            $operation['requestBody'] = [
                'required' => true,
                'content' => [
                    'application/json' => ['schema' => $capability->requestSchema],
                    AgentPayload::TOON_MEDIA_TYPE => ['schema' => $capability->requestSchema],
                ],
            ];
        }

        if ($capability->pathParameters !== []) {
            $operation['parameters'] = $capability->pathParameters;
        }

        $responseContent = $capability->responseSchema === null
            ? []
            : ['content' => [
                'application/json' => ['schema' => $capability->responseSchema],
                AgentPayload::TOON_MEDIA_TYPE => ['schema' => $capability->responseSchema],
            ]];

        $operation['responses'] = [
            '200' => ['description' => 'Success', ...$responseContent],
        ];

        return $operation;
    }
}
