/**
 * K-1 field specifications.
 *
 * Defines every box on Schedule K-1 (Form 1065) with its label, concise name,
 * field type, and panel placement.  The UI renders this spec generically — no
 * per-field switch statements needed.
 *
 * Boxes A–O → left panel (entity / partner identification)
 * Boxes 1–20 → right panel (income / deductions / credits)
 */

import { BOX11_CODES, BOX13_CODES, BOX14_CODES, BOX15_CODES, BOX16_CODES, BOX17_CODES, BOX18_CODES, BOX19_CODES, BOX20_CODES } from './k1-codes'
import type { K1FieldSpec } from './k1-types'

export const K1_SPEC: K1FieldSpec[] = [
  // ── Left panel: entity & partner identification ──────────────────────────
  {
    box: 'A',
    label: "Partnership's Employer Identification Number",
    concise: 'Partnership EIN',
    fieldType: 'text',
    side: 'left',
    uiOrder: 1,
  },
  {
    box: 'B',
    label: "Partnership's name, address, city, state, ZIP",
    concise: 'Partnership info',
    fieldType: 'multiLineText',
    side: 'left',
    uiOrder: 2,
  },
  {
    box: 'C',
    label: 'IRS Center where partnership filed return',
    concise: 'IRS center',
    fieldType: 'dropdown',
    dropdownItems: ['Ogden', 'Kansas City', 'Cincinnati'],
    side: 'left',
    uiOrder: 3,
  },
  {
    box: 'D',
    label: 'Check if this is a publicly traded partnership (PTP)',
    concise: 'PTP indicator',
    fieldType: 'check',
    side: 'left',
    uiOrder: 4,
  },
  {
    box: 'E',
    label: "Partner's identifying number",
    concise: 'Partner ID',
    fieldType: 'text',
    side: 'left',
    uiOrder: 5,
  },
  {
    box: 'F',
    label: "Partner's name, address, city, state, ZIP",
    concise: 'Partner info',
    fieldType: 'multiLineText',
    side: 'left',
    uiOrder: 6,
  },
  {
    box: 'G',
    label: 'General partner or LLC member-manager?',
    concise: 'Partner type',
    fieldType: 'dropdown',
    dropdownItems: ['General partner', 'LLC member-manager', 'Limited partner'],
    side: 'left',
    uiOrder: 7,
  },
  {
    box: 'H1',
    label: 'Domestic or foreign partner',
    concise: 'Partner residency',
    fieldType: 'dropdown',
    dropdownItems: ['Domestic', 'Foreign'],
    side: 'left',
    uiOrder: 8,
  },
  {
    box: 'H2',
    label: 'If foreign, check if U.S. person',
    concise: 'Foreign U.S. person',
    fieldType: 'check',
    side: 'left',
    uiOrder: 9,
  },
  {
    box: 'I1',
    label: "Partner's share of profit (beginning/end)",
    concise: 'Profit share',
    fieldType: 'text',
    side: 'left',
    uiOrder: 10,
  },
  {
    box: 'I2',
    label: "Partner's share of loss (beginning/end)",
    concise: 'Loss share',
    fieldType: 'text',
    side: 'left',
    uiOrder: 11,
  },
  {
    box: 'I3',
    label: "Partner's share of capital (beginning/end)",
    concise: 'Capital share',
    fieldType: 'text',
    side: 'left',
    uiOrder: 12,
  },
  {
    box: 'J',
    label: "Partner's share of liabilities",
    concise: 'Liability share',
    fieldType: 'text',
    side: 'left',
    uiOrder: 13,
  },
  {
    box: 'K',
    label: "Partner's capital account analysis",
    concise: 'Capital account',
    fieldType: 'text',
    side: 'left',
    uiOrder: 14,
  },
  {
    box: 'L',
    label: "Partner's liabilities share (recourse, nonrecourse, qualified nonrecourse)",
    concise: 'Liability categories',
    fieldType: 'dropdown',
    dropdownItems: ['Recourse', 'Nonrecourse', 'Qualified nonrecourse'],
    side: 'left',
    uiOrder: 15,
  },
  {
    box: 'M',
    label: "Partner's tax basis capital account",
    concise: 'Tax basis capital',
    fieldType: 'text',
    side: 'left',
    uiOrder: 16,
  },
  {
    box: 'N',
    label: "Partner's at-risk amount",
    concise: 'At-risk amount',
    fieldType: 'text',
    side: 'left',
    uiOrder: 17,
  },
  {
    box: 'O',
    label: "Partner's qualified liability amount",
    concise: 'Qualified liability',
    fieldType: 'text',
    side: 'left',
    uiOrder: 18,
  },

  // ── Right panel: income, deductions, credits ─────────────────────────────
  {
    box: '1',
    label: 'Ordinary business income (loss)',
    concise: 'Ordinary income',
    fieldType: 'text',
    side: 'right',
    uiOrder: 1,
  },
  {
    box: '2',
    label: 'Net rental real estate income (loss)',
    concise: 'Rental RE income',
    fieldType: 'text',
    side: 'right',
    uiOrder: 2,
  },
  {
    box: '3',
    label: 'Other net rental income (loss)',
    concise: 'Other rental income',
    fieldType: 'text',
    side: 'right',
    uiOrder: 3,
  },
  {
    box: '4',
    label: 'Guaranteed payments',
    concise: 'Guaranteed payments',
    fieldType: 'text',
    side: 'right',
    uiOrder: 4,
  },
  {
    box: '4a',
    label: 'Guaranteed payments for services',
    concise: 'GP – services',
    fieldType: 'text',
    side: 'right',
    uiOrder: 5,
  },
  {
    box: '4b',
    label: 'Guaranteed payments for capital',
    concise: 'GP – capital',
    fieldType: 'text',
    side: 'right',
    uiOrder: 6,
  },
  {
    box: '4c',
    label: 'Total guaranteed payments',
    concise: 'GP – total',
    fieldType: 'text',
    side: 'right',
    uiOrder: 7,
  },
  {
    box: '5',
    label: 'Interest income',
    concise: 'Interest income',
    fieldType: 'text',
    side: 'right',
    uiOrder: 8,
  },
  {
    box: '6a',
    label: 'Ordinary dividends',
    concise: 'Ordinary dividends',
    fieldType: 'text',
    side: 'right',
    uiOrder: 9,
  },
  {
    box: '6b',
    label: 'Qualified dividends',
    concise: 'Qualified dividends',
    fieldType: 'text',
    side: 'right',
    uiOrder: 10,
  },
  {
    box: '6c',
    label: 'Dividend equivalents',
    concise: 'Dividend equivalents',
    fieldType: 'text',
    side: 'right',
    uiOrder: 11,
  },
  {
    box: '7',
    label: 'Royalties',
    concise: 'Royalties',
    fieldType: 'text',
    side: 'right',
    uiOrder: 12,
  },
  {
    box: '8',
    label: 'Net short-term capital gain (loss)',
    concise: 'ST capital gain',
    fieldType: 'text',
    side: 'right',
    uiOrder: 13,
  },
  {
    box: '9a',
    label: 'Net long-term capital gain (loss)',
    concise: 'LT capital gain',
    fieldType: 'text',
    side: 'right',
    uiOrder: 14,
  },
  {
    box: '9b',
    label: 'Collectibles (28%) gain (loss)',
    concise: 'Collectibles gain',
    fieldType: 'text',
    side: 'right',
    uiOrder: 15,
  },
  {
    box: '9c',
    label: 'Unrecaptured section 1250 gain',
    concise: 'Sec. 1250 gain',
    fieldType: 'text',
    side: 'right',
    uiOrder: 16,
  },
  {
    box: '10',
    label: 'Net section 1231 gain (loss)',
    concise: 'Sec. 1231 gain',
    fieldType: 'text',
    side: 'right',
    uiOrder: 17,
  },
  {
    box: '11',
    label: 'Other income (loss)',
    concise: 'Other income',
    fieldType: 'buttonDetails',
    codes: BOX11_CODES,
    side: 'right',
    uiOrder: 18,
  },
  {
    box: '12',
    label: 'Section 179 deduction',
    concise: 'Sec. 179 deduction',
    fieldType: 'text',
    side: 'right',
    uiOrder: 19,
  },
  {
    box: '13',
    label: 'Other deductions',
    concise: 'Other deductions',
    fieldType: 'buttonDetails',
    codes: BOX13_CODES,
    side: 'right',
    uiOrder: 20,
  },
  {
    box: '14',
    label: 'Self-employment earnings (loss)',
    concise: 'SE income',
    fieldType: 'buttonDetails',
    codes: BOX14_CODES,
    side: 'right',
    uiOrder: 21,
  },
  {
    box: '15',
    label: 'Credits',
    concise: 'Credits',
    fieldType: 'buttonDetails',
    codes: BOX15_CODES,
    side: 'right',
    uiOrder: 22,
  },
  {
    box: '16',
    label: 'Foreign transactions',
    concise: 'Foreign transactions',
    fieldType: 'buttonDetails',
    codes: BOX16_CODES,
    side: 'right',
    uiOrder: 23,
  },
  {
    box: '17',
    label: 'Alternative minimum tax (AMT) items',
    concise: 'AMT items',
    fieldType: 'buttonDetails',
    codes: BOX17_CODES,
    side: 'right',
    uiOrder: 24,
  },
  {
    box: '18',
    label: 'Tax-exempt income and nondeductible expenses',
    concise: 'TE & nondeductible',
    fieldType: 'buttonDetails',
    codes: BOX18_CODES,
    side: 'right',
    uiOrder: 25,
  },
  {
    box: '19',
    label: 'Distributions',
    concise: 'Distributions',
    fieldType: 'buttonDetails',
    codes: BOX19_CODES,
    side: 'right',
    uiOrder: 26,
  },
  {
    box: '20',
    label: 'Other information',
    concise: 'Other info',
    fieldType: 'buttonDetails',
    codes: BOX20_CODES,
    side: 'right',
    uiOrder: 27,
  },
]

/** Quick lookup: spec entry by box identifier. */
export const K1_SPEC_BY_BOX: Record<string, K1FieldSpec> = Object.fromEntries(K1_SPEC.map((s) => [s.box, s]))

/** All coded box numbers (buttonDetails). */
export const K1_CODED_BOXES = K1_SPEC.filter((s) => s.fieldType === 'buttonDetails').map((s) => s.box)
